"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, ExternalLink, FileSearch, Inbox, Loader2, ShieldCheck, X } from "lucide-react";
import { useState } from "react";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { approveIdentityVerification, fetchIdentityVerifications, rejectIdentityVerification } from "@/lib/api/admin";

export function IdentityVerificationsPage() {
  const client = useQueryClient();
  const [page, setPage] = useState(1);
  const [rejectingId, setRejectingId] = useState<string | null>(null);
  const [reason, setReason] = useState("");
  const query = useQuery({ queryKey: ["admin", "identity-verifications", page], queryFn: () => fetchIdentityVerifications(page), retry: false });
  const approve = useMutation({ mutationFn: approveIdentityVerification, onSuccess: () => { client.invalidateQueries({ queryKey: ["admin", "identity-verifications"] }); client.invalidateQueries({ queryKey: ["admin", "overview"] }); } });
  const reject = useMutation({ mutationFn: ({ id, reason }: { id: string; reason: string }) => rejectIdentityVerification(id, reason), onSuccess: () => { setRejectingId(null); setReason(""); client.invalidateQueries({ queryKey: ["admin", "identity-verifications"] }); client.invalidateQueries({ queryKey: ["admin", "overview"] }); } });
  const error = query.error || approve.error || reject.error;

  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-extrabold tracking-tight text-brand-forest sm:text-3xl">Identity verification</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Review sellers who submitted identity documents. Approve only when both document sides are clear and belong to the applicant.</p></div><Badge variant="outline" className="bg-white">{query.data?.total ?? 0} awaiting review</Badge></div>
    {error ? <Alert className="border-red-200 bg-red-50 text-red-800"><X /><AlertTitle>Verification action could not be completed</AlertTitle><AlertDescription>{error instanceof Error ? error.message : "Please try again."}</AlertDescription></Alert> : null}
    {query.isPending ? <div className="flex min-h-56 items-center justify-center"><Loader2 className="size-6 animate-spin text-brand-forest" /></div> : !query.data?.items.length ? <Card className="border-dashed bg-white/70"><CardContent className="flex min-h-56 flex-col items-center justify-center text-center"><span className="mb-4 flex size-14 items-center justify-center rounded-2xl bg-brand-forest/5 text-brand-forest"><Inbox className="size-7" /></span><p className="font-bold text-brand-forest">No verification applications waiting</p><p className="mt-1 text-sm text-muted-foreground">New seller identity submissions will appear here.</p></CardContent></Card> : <div className="grid gap-5 lg:grid-cols-2">{query.data.items.map((item) => <Card key={item.sellerId} className="border-border/70 bg-white"><CardHeader><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between sm:gap-3"><div className="min-w-0"><CardTitle className="text-lg text-brand-forest">{item.sellerDisplayName || "Seller applicant"}</CardTitle><CardDescription>Submitted {item.submittedAt ? new Intl.DateTimeFormat("en-AE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.submittedAt)) : "recently"}</CardDescription></div><Badge className="w-fit shrink-0 border-amber-200 bg-amber-50 text-amber-900"><FileSearch />Review needed</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-2">{item.documentUrl ? <Button className="h-11" variant="outline" render={<a href={item.documentUrl} target="_blank" rel="noreferrer" />}><ExternalLink />View document front</Button> : <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">Front document unavailable</p>}{item.documentBackUrl ? <Button className="h-11" variant="outline" render={<a href={item.documentBackUrl} target="_blank" rel="noreferrer" />}><ExternalLink />View document back</Button> : <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">Back document unavailable</p>}</div><div className="rounded-xl bg-muted/50 p-3 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mr-1 inline size-4 text-brand-forest" />Check the name, photo, document clarity, and both sides before deciding.</div><div className="flex flex-col gap-2 sm:flex-row"><Button className="h-11 flex-1 font-bold" disabled={approve.isPending || reject.isPending} onClick={() => approve.mutate(item.sellerId)}>{approve.isPending && approve.variables === item.sellerId ? <Loader2 className="animate-spin" /> : <BadgeCheck />}Approve verification</Button><Button className="h-11" variant="destructive" disabled={approve.isPending || reject.isPending} onClick={() => setRejectingId(item.sellerId)}><X />Reject</Button></div></CardContent></Card>)}</div>}
    {query.data && query.data.total > query.data.pageSize ? <div className="flex items-center justify-between gap-2"><Button className="h-10" variant="outline" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</Button><span className="text-sm text-muted-foreground">Page {page}</span><Button className="h-10" variant="outline" disabled={page * query.data.pageSize >= query.data.total} onClick={() => setPage((value) => value + 1)}>Next</Button></div> : null}
    <Dialog open={Boolean(rejectingId)} onOpenChange={(open) => { if (!open) { setRejectingId(null); setReason(""); } }}><DialogContent><DialogHeader><DialogTitle>Why is this verification rejected?</DialogTitle><DialogDescription>The seller will receive this reason and can submit clearer documents again.</DialogDescription></DialogHeader><Textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Example: The document photo is blurred and the name cannot be read." className="min-h-28" /><DialogFooter showCloseButton><Button variant="destructive" disabled={!reason.trim() || reject.isPending} onClick={() => rejectingId && reject.mutate({ id: rejectingId, reason: reason.trim() })}>{reject.isPending ? <Loader2 className="animate-spin" /> : <X />}Reject and notify seller</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
