import type { Metadata } from "next";
import Link from "next/link";

import { LegalPageShell, LegalSection } from "@/features/legal";
import { getPublicAppSettings } from "@/lib/api/settings";

export const metadata: Metadata = {
  title: "Privacy Policy | Kattegat",
  description: "How Kattegat collects, uses, shares, and protects your information.",
};

export default async function PrivacyPolicyPage() {
  const settings = await getPublicAppSettings();
  const supportEmail = settings.brand.supportEmail;
  const legalName =
    settings.brand.legalName === "Kattegat"
      ? "Hidden Diversion Recreational Services"
      : settings.brand.legalName;
  const siteName = settings.brand.siteName || "Kattegat";

  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Privacy Policy"
      description={`This Privacy Policy explains what ${siteName} collects across our iOS and Android apps and website (kattegat.app), how we use it, who we share it with, and the choices you have.`}
      updatedLabel="Last updated · 15 July 2026"
    >
      <LegalSection title="1. Who we are">
        <p>
          Kattegat is operated by {legalName} (&quot;Kattegat&quot;, &quot;we&quot;, &quot;us&quot;), based in
          Dubai, United Arab Emirates. We run a direct marketplace connecting event and hospitality talent
          (&quot;sellers&quot;) with clients (&quot;buyers&quot;).
        </p>
        <p>
          This policy covers personal data processed when you browse the website, join the waitlist, create an
          account, use the mobile apps, communicate with support, or interact with marketplace features such as
          listings, requirements, chat, payments, referrals, and verification.
        </p>
      </LegalSection>

      <LegalSection title="2. Information we collect">
        <p>We collect information you provide, information generated by using Kattegat, and information from processors that help us deliver the service.</p>

        <p>
          <strong className="font-semibold text-brand-forest">Account &amp; identity</strong>
        </p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>Name, username, email, phone, business name, avatar, and password (stored via our auth provider).</li>
          <li>
            Public IDs issued at registration: BID (buyer) and/or SID (seller). Your internal account ID is a
            UUID; BID/SID are permanent public references.
          </li>
          <li>Role / dual-identity state (buyer, seller, or both on one account).</li>
        </ul>

        <p>
          <strong className="font-semibold text-brand-forest">Profile, listings &amp; marketplace content</strong>
        </p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>Seller portfolio media, bios, social links (where your plan allows), and listing fields driven by our category taxonomy.</li>
          <li>Category/subcategory, location/coverage text, pricing structures, and schema-driven listing answers.</li>
          <li>Buyer requirements (title, description, budget, dates, location, attachments) and seller applications / pitches.</li>
          <li>Quotes, invoices, bookings, client CRM notes (seller tools), and related statuses.</li>
        </ul>

        <p>
          <strong className="font-semibold text-brand-forest">Verification &amp; programmes</strong>
        </p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>Identity or business verification materials submitted for seller checks.</li>
          <li>Founding Member, White Glove / Vetted, referral, and Recommend &amp; Earn application or lead details.</li>
          <li>Waitlist submissions (name, email, Instagram, optional LinkedIn / UAE phone, role).</li>
        </ul>

        <p>
          <strong className="font-semibold text-brand-forest">Communications</strong>
        </p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>Chat messages, Contact Agent requests, admin/support conversations, and notification preferences.</li>
          <li>Reviews and ratings (when the reviews feature is enabled), including text and star ratings.</li>
        </ul>

        <p>
          <strong className="font-semibold text-brand-forest">Payments &amp; commercial records</strong>
        </p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>
            Subscription and purchase history, plan entitlements, and payment status metadata. Card numbers are
            tokenised and processed by Stripe (or a future payment provider); we do not store full PAN data.
          </li>
          <li>Wallet / reward ledger rows for referral or recommend programmes when those systems are active.</li>
        </ul>

        <p>
          <strong className="font-semibold text-brand-forest">Device, security &amp; usage</strong>
        </p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>App version, device type, push tokens, session metadata, and coarse analytics / error reports.</li>
          <li>IP address and related security signals used for rate limiting, fraud prevention, and abuse detection.</li>
          <li>City/emirate or coverage text you enter for discovery — not continuous precision GPS tracking.</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. How we use information">
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>Operate marketplace features: profiles, search/discovery ranking, listings, requirements, quotes, bookings, invoices, and chat.</li>
          <li>Authenticate users, maintain sessions, and protect accounts.</li>
          <li>Moderate listings, requirements, reviews, and reported content.</li>
          <li>Run Contact Agent / Vetted / White Glove workflows and assign operators where needed.</li>
          <li>Process subscriptions and related billing events via webhooks and entitlement sync.</li>
          <li>Send transactional messages (email / push / in-app) such as booking or moderation outcomes; marketing only where allowed.</li>
          <li>Operate referral, Founding Member, and Recommend &amp; Earn programmes.</li>
          <li>Detect fraud, self-referral abuse, fake reviews, and policy violations.</li>
          <li>Improve reliability, performance, and product quality.</li>
          <li>Meet UAE legal, tax, accounting, and dispute-resolution obligations.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. How we share information">
        <p>We do not sell your personal information. We share it only as needed to run Kattegat:</p>
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>
            <strong className="font-semibold text-brand-forest">Other users</strong> — public profile and listing
            content is visible in discovery; chat counterparts see messages; buyers/sellers see information
            required to negotiate and fulfil engagements.
          </li>
          <li>
            <strong className="font-semibold text-brand-forest">Service providers</strong> — including database and
            authentication (Supabase), media hosting/CDN (Cloudinary), payments (Stripe), caching (Upstash
            Redis), email/push providers, and error monitoring where configured.
          </li>
          <li>
            <strong className="font-semibold text-brand-forest">Kattegat operators</strong> — admin/staff accounts
            with role-based access may view user data to support moderation, Vetted cases, payouts, and safety.
            Sensitive actions are audit-logged.
          </li>
          <li>
            <strong className="font-semibold text-brand-forest">Legal &amp; advisors</strong> — where required by
            law, regulation, court order, or to protect rights, safety, and integrity of the platform.
          </li>
          <li>
            <strong className="font-semibold text-brand-forest">Business transfers</strong> — in a merger,
            acquisition, or asset sale, subject to continued protection consistent with this policy.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="5. Discovery ranking &amp; automated processing">
        <p>
          Search, browse, and Home feeds may order listings/sellers using signals such as plan priority (Starter /
          Premium / White Glove), ratings and review volume, recency, and newcomer boosts. Weights can be tuned by
          administrators. This is marketplace ranking, not automated decision-making that creates legal effects
          outside the platform display order.
        </p>
      </LegalSection>

      <LegalSection title="6. Data retention &amp; account deletion">
        <p>
          We keep personal data while your account is active and as needed to provide the service. You can delete
          your account in the Kattegat mobile app or by email. Exact in-app steps are documented on{" "}
          <Link href="/delete-account" className="font-semibold text-brand-forest underline underline-offset-2">
            Delete Your Account
          </Link>
          .
        </p>
        <p>
          On deletion we deactivate the account and remove or clear profile identifiers such as username, phone,
          and avatar. Certain financial, booking, safety, and dispute records are retained as required under UAE
          rules and to protect other users — details on the Delete Account page.
        </p>
      </LegalSection>

      <LegalSection title="7. Your rights &amp; choices">
        <ul className="list-disc space-y-2 pl-5 marker:text-brand-forest/40">
          <li>Access and update most profile fields in-app (Profile → Edit profile / Settings).</li>
          <li>Request a copy of your account data by emailing us.</li>
          <li>Request account deletion as described on the Delete Account page.</li>
          <li>Manage notification permissions on your device and in Settings → Notifications.</li>
          <li>Opt out of marketing emails via unsubscribe links (transactional mail may still be required).</li>
        </ul>
      </LegalSection>

      <LegalSection title="8. Children">
        <p>
          Kattegat is a commercial marketplace and is not directed at children. You must be at least 18 to create
          an account.
        </p>
      </LegalSection>

      <LegalSection title="9. International transfers">
        <p>
          We are based in Dubai, UAE. Some processors may store or process data in other countries. We use
          providers with appropriate security and contractual safeguards.
        </p>
      </LegalSection>

      <LegalSection title="10. Security">
        <p>
          We use industry-standard controls including encrypted transport (HTTPS), access-controlled databases,
          row-level security where applicable, webhook idempotency for payments, and staff role-based access with
          audit logging. No system is perfectly secure — use a strong unique password and protect your devices.
        </p>
      </LegalSection>

      <LegalSection title="11. Cookies &amp; similar technologies (website)">
        <p>
          The website uses minimal cookies/storage needed for operation (for example admin session cookies) and
          basic reliability. We do not use third-party advertising cookies on the launch site.
        </p>
      </LegalSection>

      <LegalSection title="12. Changes to this policy">
        <p>
          We may update this policy as Kattegat evolves. We will change the &quot;Last updated&quot; date and, for
          material changes, notify you in-app or by email where practical.
        </p>
      </LegalSection>

      <LegalSection title="13. Contact us">
        <p>
          Privacy questions:{" "}
          <a
            href={`mailto:${supportEmail}`}
            className="font-semibold text-brand-forest underline underline-offset-2"
          >
            {supportEmail}
          </a>
          .
        </p>
        <p>
          Also see our{" "}
          <Link
            href="/terms-of-service"
            className="font-semibold text-brand-forest underline underline-offset-2"
          >
            Terms of Service
          </Link>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
