import type { Metadata } from "next";
import Link from "next/link";

import { LegalPageShell, LegalSection } from "@/components/legal/legal-page-shell";
import { getPublicAppSettings } from "@/lib/api/settings";

export const metadata: Metadata = {
  title: "Privacy Policy | Kattegat",
  description: "How Kattegat collects, uses, shares, and protects your information.",
};

export default async function PrivacyPolicyPage() {
  const settings = await getPublicAppSettings();
  const supportEmail = settings.brand.supportEmail;
  const legalName = settings.brand.legalName === "Kattegat" ? "Hidden Diversion Recreational Services" : settings.brand.legalName;

  return (
    <LegalPageShell
      eyebrow="Privacy"
      title="Privacy Policy"
      description="This policy explains what information Kattegat collects across our mobile app and website, how we use it, and the choices you have."
      updatedLabel="Last updated · 10 July 2026"
    >
      <LegalSection title="1. Who we are">
        <p>
          Kattegat is operated by {legalName} (&quot;Kattegat&quot;, &quot;we&quot;, &quot;us&quot;), based in
          Dubai, United Arab Emirates. Kattegat is a direct marketplace connecting event and hospitality talent
          (&quot;sellers&quot;) with clients (&quot;buyers&quot;) across our mobile app and this website. This
          policy applies to both.
        </p>
      </LegalSection>

      <LegalSection title="2. Information we collect">
        <p>We collect information you provide directly, information generated by using Kattegat, and information from third parties involved in delivering the service.</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong className="text-brand-forest">Account information</strong> — name, username, email address,
            phone number, business name, profile photo, and password (managed securely via our authentication
            provider).
          </li>
          <li>
            <strong className="text-brand-forest">Profile &amp; listing content</strong> — portfolio photos and
            videos, service descriptions, pricing, and category details that sellers choose to publish.
          </li>
          <li>
            <strong className="text-brand-forest">Verification data</strong> — identity documents or business
            details submitted for seller verification or Founding Member / White Glove review, where applicable.
          </li>
          <li>
            <strong className="text-brand-forest">Bookings, quotes &amp; payments</strong> — requirement posts,
            quotes, invoices, booking details, and payment records. Card details are handled directly by our
            payment processor, Stripe; we do not store full card numbers.
          </li>
          <li>
            <strong className="text-brand-forest">Messages &amp; reviews</strong> — chat messages between buyers
            and sellers, inquiries, and reviews or ratings you submit.
          </li>
          <li>
            <strong className="text-brand-forest">Device &amp; usage data</strong> — app version, device type,
            push notification tokens, log data, and general usage analytics that help us keep the platform
            reliable.
          </li>
          <li>
            <strong className="text-brand-forest">Location</strong> — city/country you provide for discovery and
            search, not precise GPS tracking.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="3. How we use information">
        <ul className="list-disc space-y-2 pl-5">
          <li>Operate core features: profiles, search, requirements, quotes, bookings, invoicing, and chat.</li>
          <li>Verify identities and maintain trust and safety on the marketplace.</li>
          <li>Process payments and seller subscriptions.</li>
          <li>Send transactional notifications (booking updates, messages) and, where enabled, marketing updates.</li>
          <li>Detect, investigate, and prevent fraud, abuse, and policy violations.</li>
          <li>Improve and maintain the reliability of the app and website.</li>
          <li>Comply with legal, tax, and accounting obligations in the UAE.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. How we share information">
        <p>We do not sell your personal information. We share it only as needed to run Kattegat:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>With other users as necessary for the marketplace to function — e.g., a buyer sees a seller&apos;s public profile and portfolio; chat participants see each other&apos;s messages.</li>
          <li>With service providers who process data on our behalf, including our database and authentication provider (Supabase), media hosting (Cloudinary), payment processing (Stripe), caching infrastructure (Upstash Redis), and push/email notification providers.</li>
          <li>With professional advisors and authorities where required by law, regulation, or a valid legal request.</li>
          <li>In connection with a merger, acquisition, or sale of assets, subject to this policy continuing to apply.</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. Data retention & account deletion">
        <p>
          We keep your information for as long as your account is active and as needed to provide the service.
          You can request deletion of your account at any time — see{" "}
          <Link href="/delete-account" className="font-semibold text-brand-forest underline underline-offset-2">
            Delete Your Account
          </Link>{" "}
          for how, and exactly what is removed versus retained.
        </p>
        <p>
          In short: your profile, name, and contact details are removed on deletion. Booking, invoice, and
          payment records are retained as required for UAE tax and financial reporting obligations, and to
          resolve disputes, consistent with financial record-keeping requirements.
        </p>
      </LegalSection>

      <LegalSection title="6. Your rights & choices">
        <ul className="list-disc space-y-2 pl-5">
          <li>Access and update most of your profile information directly in the app.</li>
          <li>Request a copy of your account data by contacting us.</li>
          <li>Request deletion of your account as described above.</li>
          <li>Manage push and email notification preferences in-app.</li>
          <li>Opt out of marketing emails via the unsubscribe link in any marketing message.</li>
        </ul>
      </LegalSection>

      <LegalSection title="7. Children">
        <p>
          Kattegat facilitates commercial event and hospitality bookings and is not directed at children. You
          must be at least 18 years old to create an account.
        </p>
      </LegalSection>

      <LegalSection title="8. International transfers">
        <p>
          Kattegat is based in Dubai, UAE. Some of our service providers may process data outside the UAE. Where
          this happens, we rely on providers with appropriate security and contractual safeguards in place.
        </p>
      </LegalSection>

      <LegalSection title="9. Security">
        <p>
          We use industry-standard safeguards — including encrypted connections, access-controlled databases, and
          row-level security on our data store — to protect your information. No system is perfectly secure, and
          we encourage you to use a strong, unique password.
        </p>
      </LegalSection>

      <LegalSection title="10. Cookies (website)">
        <p>
          Our website uses minimal cookies and similar technologies needed to operate the site, remember your
          session, and understand aggregate usage. We do not use them for third-party advertising.
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to this policy">
        <p>
          We may update this policy as Kattegat evolves. We&apos;ll update the &quot;Last updated&quot; date
          above, and where changes are material, we&apos;ll notify you in-app or by email.
        </p>
      </LegalSection>

      <LegalSection title="12. Contact us">
        <p>
          Questions about this policy or your data can be sent to{" "}
          <a href={`mailto:${supportEmail}`} className="font-semibold text-brand-forest underline underline-offset-2">
            {supportEmail}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
